apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: history
          image: $CONTAINER_REGISTRY/history:$VERSION
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "4001"
            - name: DBHOST
              value: mongodb://db:27017
            - name: DBNAME
              value: history
            - name: NODE_ENV
              value: development
            - name: RABBIT
              value: amqp://guest:guest@rabbit:5672
---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  selector:
    app: history
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
