apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers:
        - name: recommendations
          image: $CONTAINER_REGISTRY/recommendations:$VERSION
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "4003"
            - name: DBHOST
              value: mongodb://db:27017
            - name: DBNAME
              value: recommendations
            - name: NODE_ENV
              value: development
            - name: RABBIT
              value: amqp://guest:guest@rabbit:5672
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations
spec:
  selector:
    app: recommendations
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4003
