name: CI

on:
  #
  # Runs tests against the microservice on push to the main branch of this code repository.
  #
  push: 
    branches:
      - main

  #
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - run: pnpm install --frozen-lockfile
    - run: npm test
  package:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - run: echo " packaging..."
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - run: echo " deploying..."
